---
apiVersion: imgpkg.carvel.dev/v1alpha1
images:
- annotations:
    kbld.carvel.dev/id: ghcr.io/making/tsunagu-server
    kbld.carvel.dev/origins: |
      - resolved:
          tag: latest
          url: ghcr.io/making/tsunagu-server
  image: ghcr.io/making/tsunagu-server@sha256:ae2140bf1aec21ec4543f3811d62e75fd5220ca3300359608f75928c63b6717e
kind: ImagesLock
