#@ load("@ytt:data", "data")
#@ if/end data.values.tsunagu.create_namespace:
---
apiVersion: v1
kind: Namespace
metadata:
  name: #@ data.values.tsunagu.namespace
---
apiVersion: v1
kind: Service
metadata:
  name: tsunagu-server
  namespace: #@ data.values.tsunagu.namespace
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  - name: actuator
    port: 9090
  selector:
    app.kubernetes.io/part-of: tsunagu-server
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tsunagu-server
  namespace: #@ data.values.tsunagu.namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/part-of: tsunagu-server
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: tsunagu-server
    spec:
      containers:
      - name: tsunagu-server
        image: ghcr.io/making/tsunagu-server
        env:
        - name: SPRING_CONFIG_IMPORT
          value: configtree:/config/
        ports:
        - name: web
          containerPort: 8080
        - name: actuator
          containerPort: 9090
        resources:
          limits:
            memory: "200Mi"
          requests:
            memory: "200Mi"
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 9090
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 9090
        volumeMounts:
        - name: tsunagu
          mountPath: /config/tsunagu
          readOnly: true
      volumes:
      - name: tsunagu
        secret:
          secretName: tsunagu
---
apiVersion: v1
kind: Secret
metadata:
  name: tsunagu
  namespace: #@ data.values.tsunagu.namespace
type: Opaque
stringData:
  token: #@ data.values.tsunagu.token
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: tsunagu
  namespace: #@ data.values.tsunagu.namespace
spec:
  virtualhost:
    fqdn: #@ data.values.tsunagu.fqdn
    tls:
      secretName: #@ "{}-tls".format(data.values.tsunagu.fqdn)
  routes:
  - conditions:
    - prefix: /tsunagu
    enableWebsockets: true
    services:
    - name: tsunagu-server
      port: 80
  - conditions:
    - prefix: /rsocket
    enableWebsockets: true
    services:
    - name: tsunagu-server
      port: 80
  - conditions:
    - prefix: /actuator
    services:
    - name: tsunagu-server
      port: 9090
  - conditions:
    - prefix: /
    services:
    - name: tsunagu-server
      port: 80
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tsunagu-ik-am
  namespace: #@ data.values.tsunagu.namespace
spec:
  secretName: #@ "{}-tls".format(data.values.tsunagu.fqdn)
  issuerRef:
    kind: #@ data.values.tsunagu.issuer.kind
    name: #@ data.values.tsunagu.issuer.name
  dnsNames:
  - #@ data.values.tsunagu.fqdn