name: ci
on:
  push:
    branches:
    - main
    paths:
    - tsunagu-server/**
    - tsunagu-client/**
    - pom.xml
    - .github/workflows/ci.yaml
  pull_request:
    branches:
    - main
    paths:
    - tsunagu-server/**
    - tsunagu-client/**
    - pom.xml
    - .github/workflows/ci.yaml
jobs:
  build-server:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - uses: graalvm/setup-graalvm@v1
      with:
        version: 'latest'
        java-version: '11'
        components: 'native-image'
    - name: build
      run: |
        set -ex
        cd ${GITHUB_WORKSPACE}/tsunagu-server
        ./mvnw clean package -DskipTests -V -Pnative,mostly-static
        unzip target/*.zip -d ../dist
        rm -f ../dist/Procfile
    - uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist/*
  build-client:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - uses: graalvm/setup-graalvm@v1
      with:
        version: 'latest'
        java-version: '11'
        components: 'native-image'
    - name: build
      run: |
        set -ex
        cd ${GITHUB_WORKSPACE}/tsunagu-client
        ./mvnw clean package -DskipTests -V -Pnative,mostly-static
        unzip target/*.zip -d ../dist
        rm -f ../dist/Procfile
    - uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist/*
